### ISSUE TITLE
Customizing an xsl file

### ISSUE THREAD

**Issue by CamilleGh** [ori229/print-bib-record#5]
Hello,

I'm trying to customize an xsl file for the print bib record cloud app.
I would like to retrieve some data from the fixed fields like it's done in the MARC21slim2English.xsl for the Leader. 

I can obtain the value of the whole field like that :
<xsl:template match="controlfield[@tag='008']">
          <li>008:
       <xsl:value-of select="controlfield[@tag='008']" />
<xsl:value-of select="."/>
          </li>
      </xsl:template>

But not for a character position like the language or the date. I tried differents combinations but I always get an error message or no data at all.
For exemple like that : <xsl:variable name="controlfield23" select="substring(marc:controlfield[@tag=008],3,35)"/>
			<xsl:value-of select="substring(marc:controlfield[@tag=008],3,35)"/>

Can you help ?
Kind regards
Camille

**Comment by ori229** [comment]
Hi Camille,
This should work:
<xsl:value-of select="substring(controlfield[@tag='008'],3,4)" />
If you write a nice template please share here - we can add it to the official App.
Thanks,
Liron & Ori
